DATA:
  HEIGHT: 384
  WIDTH: 192
  TRAIN_BATCH: 96
  NUM_INSTANCES: 12
  TEST_BATCH: 512
TRAIN:
  OPTIMIZER:
    NAME: 'adam'
    LR: 0.0003
  lr_type: 'step'
  MAX_EPOCH: 1200
  LR_SCHEDULER:
    STEPSIZE: [30, 60, 90]
TEST:
  EVAL_STEP: 5
SEED: 1
# EVAL_MODE: True
MODEL:
  NAME: resnet50
  # RESUME: '/public/home/G19830015/VideoGroup/lmy/Simple-ReID/logs/prcc/384*192batch64-gs-ras-ma-ma(epoch)/checkpoint_ep47.pth.tar'
LOSS:
  CLA_LOSS: crossentropy
  PAIR_LOSS: triplet
  PAIR_M: 0.3
  CENTER_LOSS: False    
  CENTER_LOSS_WEIGHT: 0.0001
TAG: 384*192batch96-gs-ras2-ma-mb(36-0.0003.0)
